"""
Segment A — Hotel & Resort Knowledge Base (Part 2)
Categories: Dining, Spa & Wellness, Activities, Facilities
~200 entries
"""

DOCS = [
    # ═══════════════════════════════════════════════════════════════
    # DINING — Restaurants, Room Service, Dietary (~80)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "dining", "title": "Restaurant Overview",
     "content": "Q: What restaurants do you have?\nA: We have three dining outlets:\n• Horizon Café — all-day dining, international & local buffet (7am–10pm)\n• Sunset Grill — Western steaks & seafood, à la carte (6pm–11pm)\n• Poolside Bar — light bites, cocktails & mocktails (10am–8pm)\nAll outlets welcome both in-house and walk-in guests!"},
    {"doc_type": "dining", "title": "Breakfast Buffet Details",
     "content": "Q: What time is breakfast and what's available?\nA: Breakfast is served at Horizon Café from 7:00 AM to 10:30 AM daily. Our buffet features over 80 items including Western (eggs any style, bacon, sausages, pastries), Asian (nasi lemak, dim sum, congee, roti canai), fresh fruits, cereals, and a live egg station. It's quite a spread!"},
    {"doc_type": "dining", "title": "Breakfast — Nasi Lemak",
     "content": "Q: Do you serve nasi lemak for breakfast?\nA: Of course — this is Malaysia! Our nasi lemak is one of the breakfast highlights, prepared fresh every morning with fragrant coconut rice, sambal, anchovies, peanuts, and a choice of rendang or ayam goreng. Many guests come back just for this!"},
    {"doc_type": "dining", "title": "Halal Certification",
     "content": "Q: Is your food halal?\nA: Yes, our entire kitchen operation is halal-certified by JAKIM. All ingredients are sourced from halal-certified suppliers. We take pride in ensuring all our Muslim guests can dine with complete peace of mind."},
    {"doc_type": "dining", "title": "Vegetarian & Vegan Options",
     "content": "Q: Do you cater for vegetarians?\nA: Absolutely! Each restaurant has a dedicated vegetarian section on the menu. For vegans, our chefs are happy to prepare dishes without dairy or animal products. Please inform us of your dietary requirements when booking or upon arrival, and we'll ensure every meal is perfect for you."},
    {"doc_type": "dining", "title": "Food Allergies & Special Diets",
     "content": "Q: My child has a nut allergy. Can you accommodate?\nA: Your child's safety is our top priority. Please inform us of any allergies at check-in. Our kitchen maintains an allergen management protocol and our chefs will personally ensure every dish served is safe. We can also prepare special meals upon advance request."},
    {"doc_type": "dining", "title": "Sunset Grill — Signature Dishes",
     "content": "Q: What's good at Sunset Grill?\nA: Our chef's recommendations include the Grilled Australian Ribeye (RM135), Butter Garlic Tiger Prawns (RM95), and the Seafood Platter for Two (RM220). For a special evening, try our 5-Course Chef's Table experience at RM280/person with wine pairing. Reservations recommended, especially on weekends!"},
    {"doc_type": "dining", "title": "Poolside Bar Menu",
     "content": "Q: Can we eat by the pool?\nA: Yes! Our Poolside Bar serves from 10 AM to 8 PM daily. The menu includes burgers (RM38), pizzas (RM32), satay platters (RM28), fresh juices (RM18), cocktails (RM32), and mocktails (RM22). You can order directly from your sun lounger — our team will come to you!"},
    {"doc_type": "dining", "title": "Room Service Menu & Hours",
     "content": "Q: Is room service available?\nA: Room service is available from 6:30 AM to midnight (full menu) and from midnight to 6:30 AM (limited night menu — sandwiches, soups, desserts). A 15% service charge applies. Orders arrive within 25–30 minutes. In-room dining menus are in your room or available via the in-room tablet."},
    {"doc_type": "dining", "title": "Birthday Cake Order",
     "content": "Q: Can you arrange a birthday cake?\nA: We'd love to! Our pastry chef can prepare a custom cake with 48 hours notice. Options range from RM120 (6-inch, serves 6–8) to RM280 (10-inch, serves 15–20). Flavours include chocolate, red velvet, tropical fruit, and pandan — a local favourite! Just let me know the name and any message for the cake."},
    {"doc_type": "dining", "title": "Private Dining Arrangements",
     "content": "Q: Can we have a private dinner for an anniversary?\nA: How romantic! We can arrange a private beachside dinner for two complete with a 4-course meal, candles, flowers, and a personal waiter. Packages start from RM500/couple. Garden pavilion and rooftop options are also available. Shall I arrange something special?"},
    {"doc_type": "dining", "title": "Children's Menu",
     "content": "Q: Do you have a kids' menu?\nA: Yes! Our kids' menu (available at all outlets) features favourites like chicken nuggets (RM22), fish fingers (RM20), pasta (RM18), mini burgers (RM25), and ice cream sundaes (RM15). Portions are sized for children 4–12. High chairs and booster seats are always available."},
    {"doc_type": "dining", "title": "Afternoon Tea",
     "content": "Q: Do you serve afternoon tea?\nA: Our Grand Afternoon Tea at the lobby lounge is served daily from 3:00 PM to 5:00 PM. It features a three-tier selection of scones, finger sandwiches, local kuih, and petit fours, plus your choice of premium tea or coffee. RM88 per person or RM158 for two. A lovely way to spend the afternoon!"},
    {"doc_type": "dining", "title": "Coffee & Tea Options",
     "content": "Q: Where can I get good coffee?\nA: Our lobby lounge serves premium coffee from 7 AM to 10 PM — espresso, cappuccino, latte, and our signature iced Malaysian white coffee. Each room also has a Nespresso machine with 4 capsules replenished daily. For something local, try our teh tarik — our barista makes it just right!"},
    {"doc_type": "dining", "title": "Midnight Snack Options",
     "content": "Q: Can I order food after midnight?\nA: Our night menu is available from midnight to 6:30 AM via room service. Options include club sandwiches (RM35), noodle soup (RM28), fresh fruit platter (RM25), and a selection of desserts. Hot drinks and beverages are available 24/7. Perfect for those late-night cravings!"},
    {"doc_type": "dining", "title": "Dress Code for Restaurants",
     "content": "Q: Is there a dress code?\nA: Horizon Café and Poolside Bar are smart casual — beachwear with a cover-up is fine. Sunset Grill requests smart casual in the evening (collared shirts for gentlemen, no flip-flops). We keep it relaxed while maintaining a pleasant atmosphere for everyone."},
    {"doc_type": "dining", "title": "Restaurant Reservations",
     "content": "Q: Do I need to book for dinner?\nA: For Horizon Café (buffet), reservations aren't usually needed. For Sunset Grill, we strongly recommend reservations, especially on Friday and Saturday evenings. You can book through the front desk, in-room phone, or just let me know here and I'll reserve for you!"},
    {"doc_type": "dining", "title": "Alcohol Availability",
     "content": "Q: Do you serve alcohol?\nA: Yes, all three outlets serve a full range of alcoholic beverages including cocktails, wines, beers, and spirits. We also have an excellent selection of non-alcoholic cocktails (mocktails). Our Poolside Bar happy hour is 4–6 PM daily with selected drinks at 50% off!"},
    {"doc_type": "dining", "title": "Local Malaysian Cuisine",
     "content": "Q: Do you serve local food?\nA: Absolutely! Our Horizon Café features a dedicated Malaysian corner with rotating dishes — laksa, char kway teow, satay, rendang, Tom yam, and more. Every Thursday is our special Malaysian Night with a live cooking station. We celebrate our rich food heritage with pride!"},
    {"doc_type": "dining", "title": "Takeaway & Packed Meals",
     "content": "Q: Can we take food for a day trip?\nA: Yes! We can prepare packed meals for day excursions. Options include sandwich packs (RM35) or nasi lemak bungkus (RM25). Please order the night before and we'll have them ready by 7 AM. We'll also include bottled water and snacks. Perfect for island hopping!"},

    # ═══════════════════════════════════════════════════════════════
    # SPA & WELLNESS (~60)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "spa", "title": "Spa Overview & Operating Hours",
     "content": "Q: Tell me about your spa.\nA: Our Serenity Spa offers a tranquil escape with 8 treatment rooms, a couples' suite, sauna, steam room, and relaxation lounge. Open daily from 10 AM to 9 PM. Treatments blend traditional Malay healing techniques with modern wellness. We recommend booking in advance, especially on weekends."},
    {"doc_type": "spa", "title": "Spa Treatment Menu — Massage",
     "content": "Q: What massages do you offer?\nA: Our massage menu includes:\n• Traditional Malay Urut: 60 min RM180 / 90 min RM250\n• Balinese Relaxation: 60 min RM200 / 90 min RM280\n• Deep Tissue Sports: 60 min RM220 / 90 min RM300\n• Hot Stone Therapy: 90 min RM320\n• Foot Reflexology: 45 min RM120\nAll treatments include complimentary herbal tea and a relaxation period."},
    {"doc_type": "spa", "title": "Couples Spa Package",
     "content": "Q: Do you have spa packages for couples?\nA: Our 'Harmony for Two' package is perfect — 90-minute couples massage in our private suite, followed by a flower bath and a glass of champagne. RM650/couple. We also have a 'Romance Retreat' half-day package at RM1,200 including body scrub, massage, facial, and light refreshments."},
    {"doc_type": "spa", "title": "Spa Booking & Cancellation",
     "content": "Q: How do I book a spa treatment?\nA: You can book via WhatsApp (right here!), at the front desk, or by calling extension 9. We recommend booking at least 24 hours in advance, especially for couples' treatments and weekends. Cancellations within 4 hours of appointment time will incur a 50% charge."},
    {"doc_type": "spa", "title": "Gym & Fitness Centre",
     "content": "Q: Do you have a gym?\nA: Our Fitness Centre is open 24/7 for in-house guests, equipped with treadmills, ellipticals, stationary bikes, free weights, cable machines, and kettlebells. Towels and water are provided. We also offer complimentary morning yoga sessions on the lawn (Mon, Wed, Fri at 7 AM)."},
    {"doc_type": "spa", "title": "Sauna & Steam Room",
     "content": "Q: Is there a sauna?\nA: Yes! Our wet facility area includes a dry sauna (Finnish-style) and a steam room. Both are located next to the pool area and are available from 7 AM to 9 PM. Complimentary for in-house guests. Robes and towels are provided at the spa reception."},
    {"doc_type": "spa", "title": "Swimming Pool Details",
     "content": "Q: Tell me about the pool.\nA: Our infinity pool (25m) overlooks the garden and features a swim-up bar, jacuzzi section, and dedicated children's wading pool (30cm depth). Open daily 7 AM to 10 PM. Pool towels are provided at the pool deck. Lifeguard on duty from 9 AM to 6 PM."},
    {"doc_type": "spa", "title": "Children's Pool Area",
     "content": "Q: Is the pool safe for young children?\nA: We have a separate children's wading pool (30cm depth) with soft-surface flooring, water features, and shade covers. Children under 12 must be supervised by an adult at all times. Arm floats and pool toys are available from the pool attendant. The area is fenced for added safety."},
    {"doc_type": "spa", "title": "Pool Rules",
     "content": "Q: Are there any pool rules?\nA: For everyone's enjoyment: no glass containers at the pool deck, supervise children at all times, shower before entering the pool, and maintain appropriate swimwear. Our pool has a shallow end (1.2m) and a deep end (1.8m). Floats and inflatables are available from the pool attendant."},
    {"doc_type": "spa", "title": "Yoga & Wellness Classes",
     "content": "Q: Do you offer yoga or fitness classes?\nA: We offer complimentary wellness activities:\n• Morning Yoga on the Lawn: Mon, Wed, Fri at 7 AM\n• Aqua Aerobics: Tue, Thu at 8 AM\n• Tai Chi in the Garden: Sat at 7 AM\nPrivate yoga sessions can be arranged at RM150/hour. All levels welcome — even absolute beginners!"},
    {"doc_type": "spa", "title": "Facial Treatments",
     "content": "Q: Do you offer facial treatments?\nA: Our facial menu includes:\n• Hydrating Marine Facial: 60 min RM180\n• Anti-Ageing Vitamin C Boost: 75 min RM250\n• Deep Cleansing Purify: 60 min RM160\n• Men's Skin Revival: 60 min RM160\nAll facials include skin consultation and use premium botanical products sourced locally."},
    {"doc_type": "spa", "title": "Body Scrub & Wrap Options",
     "content": "Q: What body treatments do you have?\nA: Our body treatment menu features:\n• Malay Lulur Body Scrub: 45 min RM150 (traditional turmeric & rice)\n• Coffee & Coconut Body Polish: 45 min RM160\n• Seaweed Detox Wrap: 60 min RM200\n• Tropical Fruit Body Mask: 45 min RM180\nThese pair beautifully with a massage for a full spa experience!"},
    {"doc_type": "spa", "title": "Spa Etiquette & What to Bring",
     "content": "Q: What should I bring to the spa?\nA: Just yourself! We provide everything — robes, slippers, towels, shower amenities, complimentary herbal tea, and a secure locker for your belongings. We recommend arriving 15 minutes early to enjoy the relaxation lounge. Spa attire is provided for all treatments."},
    {"doc_type": "spa", "title": "Spa Gift Vouchers",
     "content": "Q: Can I buy a spa gift voucher?\nA: Absolutely! Spa gift vouchers make a wonderful present. Available in any denomination from RM100, or for specific treatments. Valid for 12 months. We can arrange a beautifully packaged physical voucher or an instant digital version. Perfect for birthdays, anniversaries, or just because!"},

    # ═══════════════════════════════════════════════════════════════
    # ACTIVITIES & EXCURSIONS (~60)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "activities", "title": "Activities Overview",
     "content": "Q: What activities do you offer?\nA: We have plenty to keep you entertained! On-site: pool, gym, spa, tennis court, bicycle hire, nature walks, cultural shows. Off-site: island hopping, snorkelling, waterfall treks, ATV rides, and local food tours. Our concierge can arrange everything for you. What interests you most?"},
    {"doc_type": "activities", "title": "Island Hopping Tours",
     "content": "Q: Can you arrange island hopping?\nA: Yes! Our popular island-hopping package includes visits to 3 islands with snorkelling stops, a beach BBQ lunch, and boat transfers. Full-day tour (9 AM–4 PM) at RM180/adult and RM120/child. We partner with licensed operators and include life jackets and snorkel gear. Book 1 day ahead."},
    {"doc_type": "activities", "title": "Snorkelling & Diving",
     "content": "Q: Is there snorkelling nearby?\nA: The marine park is just 15 minutes by boat! Snorkelling trips depart daily at 9:30 AM and 2 PM. RM80/person including gear rental. For diving, we partner with a PADI-certified centre offering discover scuba dives (RM250) and certified dives (RM180/dive). The coral reefs here are simply beautiful!"},
    {"doc_type": "activities", "title": "Waterfall Trekking",
     "content": "Q: Are there waterfalls nearby?\nA: There are two beautiful waterfalls within 30 minutes. We arrange guided jungle treks (half-day, RM100/person) that include transport, a nature guide, and light refreshments. The trail is moderate difficulty and suitable for ages 8+. Wear comfortable shoes and bring insect repellent — we'll provide everything else!"},
    {"doc_type": "activities", "title": "Bicycle Rental",
     "content": "Q: Can we rent bicycles?\nA: Complimentary mountain bikes are available for in-house guests from 7 AM to 6 PM. We have adult and children's sizes, plus baby seats. Helmets provided. Our concierge can suggest scenic cycling routes ranging from easy coastal paths (5 km) to challenging hill trails (15 km)."},
    {"doc_type": "activities", "title": "Tennis Court",
     "content": "Q: Do you have a tennis court?\nA: We have one floodlit tennis court available from 7 AM to 10 PM. Complimentary for in-house guests. Rackets and balls can be borrowed from the recreation desk. Court booking is required and can be done at the front desk or via extension 7. Private coaching available at RM100/hour."},
    {"doc_type": "activities", "title": "Cultural Show & Local Experiences",
     "content": "Q: Are there any cultural shows?\nA: Every Saturday evening at 8 PM, we host a complimentary Malaysian Cultural Night on the garden terrace — featuring traditional dance performances, dikir barat, and a batik-painting demonstration. It's a highlight for many guests. We also arrange kampung (village) visits for a taste of authentic Malaysian life."},
    {"doc_type": "activities", "title": "Kids' Club & Children's Activities",
     "content": "Q: Do you have activities for kids?\nA: Our Little Explorers Kids' Club operates daily from 9 AM to 5 PM for ages 4–12. Activities include arts & crafts, treasure hunts, movie time, pool games, and nature walks. Supervision is provided by our trained team. Complimentary for in-house guests! Parents enjoy some well-deserved relaxation time."},
    {"doc_type": "activities", "title": "Water Sports",
     "content": "Q: What water sports are available?\nA: At our water sports centre (open 9 AM–5 PM):\n• Kayaking: RM60/hour\n• Stand-up paddleboarding: RM70/hour\n• Jet skiing: RM150/30 min\n• Banana boat rides: RM50/person\n• Parasailing: RM180/person\nAll activities include safety gear and a safety briefing. Minimum age varies by activity."},
    {"doc_type": "activities", "title": "Sunset Cruise",
     "content": "Q: Do you have sunset cruise options?\nA: Our sunset cruise departs at 5:30 PM daily (45 minutes). RM120/adult, RM80/child. Includes welcome drink and canapés as you watch the sun dip below the horizon. It's truly magical. Private charters for up to 10 guests are available from RM800. Highly recommended for couples!"},
    {"doc_type": "activities", "title": "Fishing Trip",
     "content": "Q: Can you arrange a fishing trip?\nA: Yes! We offer half-day fishing trips (8 AM–12 PM) at RM200/person, minimum 2 pax. Includes boat, fishing equipment, bait, and beverages. If you're lucky with your catch, our chef can prepare it for your dinner — grilled, steamed, or fried! Advanced booking recommended."},
    {"doc_type": "activities", "title": "Cooking Class — Malaysian Cuisine",
     "content": "Q: Do you have cooking classes?\nA: Our 'Taste of Malaysia' cooking class runs every Wednesday and Saturday, 10 AM–1 PM. Learn to prepare 3 authentic Malaysian dishes from our chef — typically nasi lemak, rendang, and a local dessert. RM150/person including all ingredients, recipe cards, and lunch. A wonderful souvenir experience!"},
    {"doc_type": "activities", "title": "ATV Adventure",
     "content": "Q: Is there ATV riding available?\nA: We partner with a certified ATV adventure centre 20 minutes away. Trails range from beginner-friendly (30 min, RM80) to advanced jungle tracks (2 hours, RM200). Minimum age 16 for solo riding, children 8+ can ride pillion with a guide. Transport arranged from the hotel."},
    {"doc_type": "activities", "title": "Golf Nearby",
     "content": "Q: Is there a golf course nearby?\nA: The Horizon Golf Club is just 15 minutes away — an 18-hole championship course with ocean views. Green fees from RM180 (weekday) and RM280 (weekend). We can arrange tee times, transport, and equipment rental. Our concierge has a special rate for hotel guests."},
    {"doc_type": "activities", "title": "Night Market & Local Shopping",
     "content": "Q: Is there a night market nearby?\nA: Yes! The local pasar malam (night market) operates every Wednesday and Saturday evening, just 10 minutes by car. You'll find incredible local street food (from RM3!), handicrafts, batik, and souvenirs. We can arrange transport or you're welcome to borrow our complimentary bicycles."},
    {"doc_type": "activities", "title": "Rainy Day Activities",
     "content": "Q: What can we do if it rains?\nA: Plenty! Indoor options include our spa, gym, games room (pool table, board games, PS5), in-room movies via smart TV, cooking classes, batik painting workshops, and afternoon tea at the lobby lounge. Our library lounge also has a wonderful collection of books and magazines. Rain won't dampen your holiday!"},
    {"doc_type": "activities", "title": "Photography Tours",
     "content": "Q: Can you arrange a professional photography session?\nA: We work with talented local photographers who offer:\n• Family portrait sessions: RM350 (1 hour, 30 edited photos)\n• Couple/proposal shoots: RM500 (90 min, sunset setting)\n• Drone aerial photography: RM300 (30 min)\nThe resort grounds and nearby beaches make stunning backdrops!"},

    # ═══════════════════════════════════════════════════════════════
    # FACILITIES — General Property Facilities (~50)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "facilities", "title": "Wi-Fi & Internet Access",
     "content": "Q: Is there free Wi-Fi?\nA: Yes! Complimentary high-speed Wi-Fi is available throughout the entire property — in rooms, lobby, restaurants, pool area, and garden. Speed is 100 Mbps, sufficient for video calls and streaming. Simply connect to 'GrandHorizon_WiFi' — no password needed. In-room Ethernet ports are also available for those who prefer wired connections."},
    {"doc_type": "facilities", "title": "Parking Facilities",
     "content": "Q: Is there parking?\nA: We offer complimentary parking for all in-house guests. Our open-air car park accommodates 150 vehicles. Covered parking (limited spaces) is available on a first-come-first-served basis. Valet parking is available at RM20/day. EV charging stations (2 bays, Type 2) are also available for electric vehicles."},
    {"doc_type": "facilities", "title": "Business Centre",
     "content": "Q: Do you have a business centre?\nA: Our Business Centre on the mezzanine floor operates 24/7 (keycard access). It offers 4 workstations with PCs, high-speed internet, a printer/scanner/copier (B&W RM1/page, colour RM3/page), and a private phone booth. We also have portable projectors and screens available for loan."},
    {"doc_type": "facilities", "title": "Meeting & Event Rooms",
     "content": "Q: Do you have meeting rooms?\nA: We have 3 meeting rooms and 1 grand ballroom:\n• Boardroom — 12 pax, RM200/half day\n• Mergui Room — 30 pax, RM400/half day\n• Andaman Room — 80 pax, RM800/half day\n• Grand Ballroom — 300 pax, from RM3,000\nAll include complimentary Wi-Fi, projector, and water service. AV equipment and F&B packages available."},
    {"doc_type": "facilities", "title": "Prayer Room / Surau",
     "content": "Q: Is there a prayer room?\nA: Yes, we have a dedicated surau (prayer room) on the ground floor near the lobby, open 24 hours. It accommodates approximately 30 persons with separate sections for men and women. Prayer mats, telekung, and sajadah are provided. Qibla direction is clearly marked."},
    {"doc_type": "facilities", "title": "Laundry & Dry Cleaning",
     "content": "Q: Do you have laundry service?\nA: Yes! Our laundry services include:\n• Wash & fold: from RM10/item\n• Dry cleaning: from RM25/item\n• Express service (3 hours): 50% surcharge\n• Self-service launderette: RM15/load (wash & dry)\nCollected before 9 AM, returned by 6 PM same day. Laundry bags and forms are in your wardrobe."},
    {"doc_type": "facilities", "title": "Gift Shop & Convenience Store",
     "content": "Q: Is there a shop on-site?\nA: Our lobby gift shop (open 8 AM–10 PM) stocks local souvenirs, batik items, postcards, sunscreen, toiletries, snacks, SIM cards, and basic medicines. There's also a convenience store (7 AM–11 PM) with drinks, instant noodles, baby supplies, and other essentials. A 24-hour vending machine is located near the gym."},
    {"doc_type": "facilities", "title": "ATM & Currency Exchange",
     "content": "Q: Is there an ATM?\nA: There's a Maybank ATM in the lobby (supports Visa, Mastercard, and international cards). Currency exchange is available at the front desk during operating hours (8 AM–8 PM) for major currencies (USD, SGD, EUR, GBP, AUD, JPY, CNY). Rates are competitive and updated daily."},
    {"doc_type": "facilities", "title": "Medical & First Aid",
     "content": "Q: Is there medical assistance available?\nA: Our front desk maintains a comprehensive first-aid kit available 24/7. For medical emergencies, the nearest hospital is 15 minutes away by car. We can arrange a hotel doctor visit (on-call, RM150 consultation fee). Common medicines (paracetamol, plasters, etc.) are available from the front desk or gift shop."},
    {"doc_type": "facilities", "title": "Library Lounge",
     "content": "Q: Is there a reading area?\nA: Our Library Lounge on the mezzanine floor offers a peaceful escape with comfortable armchairs, natural light, and a collection of 500+ books covering fiction, travel, business, and Malaysian culture. Complimentary tea and coffee are available. Guests are welcome to borrow books for their stay."},
    {"doc_type": "facilities", "title": "Garden & Green Spaces",
     "content": "Q: Tell me about the grounds.\nA: Our 8-acre property features tropical gardens with indigenous plants, a landscaped jogging path (1.5 km loop), a Zen garden with koi pond, and a sunset viewing deck. The grounds are beautifully lit in the evening and perfect for an after-dinner stroll. Our gardening team maintains over 200 species of tropical plants!"},
    {"doc_type": "facilities", "title": "Elevator & Accessibility",
     "content": "Q: How many floors and lifts?\nA: The resort is 10 floors with 3 passenger lifts and 1 service lift. All lifts have braille buttons and audio announcements. Wheelchair access is available throughout all public areas. Ground-floor accessible rooms are available for guests with mobility requirements."},
    {"doc_type": "facilities", "title": "Safety & Security",
     "content": "Q: How safe is the property?\nA: Guest safety is our top priority. We have 24/7 CCTV coverage, trained security personnel at all entry points, electronic keycard access to room floors, in-room electronic safes, and fire safety systems throughout. Emergency exits are well-marked. Our team undergoes regular safety training."},
    {"doc_type": "facilities", "title": "Smoking Areas",
     "content": "Q: Where can I smoke?\nA: The entire indoor area is non-smoking. Designated smoking areas are located at the garden terrace (ground floor) and the outdoor section of the Poolside Bar. Ashtrays are provided at these locations. We appreciate your cooperation in keeping the air clean for all guests."},
    {"doc_type": "facilities", "title": "Lost & Found",
     "content": "Q: I left something at the hotel.\nA: No worries! Please contact our front desk with a description of the item and your room/checkout date. We maintain a lost & found registry for 90 days. If found, we can courier the item to you — shipping costs will apply depending on destination. We'll do our best to reunite you with your belongings!"},
]
