"""
Segment A — Hotel & Resort Knowledge Base (Part 1)
Categories: Rooms, Rates, Reservations, Check-in/Check-out
~250 entries
"""

DOCS = [
    # ═══════════════════════════════════════════════════════════════
    # ROOMS — Room Types & Amenities (~80)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "rooms", "title": "Deluxe King Room — Layout & Amenities",
     "content": "Q: What's included in the Deluxe King room?\nA: Our Deluxe King (42 sqm) comes with a plush king-sized bed dressed in premium Egyptian cotton linens, a walk-in rain shower, complimentary high-speed Wi-Fi, Nespresso machine, fully stocked minibar, 55-inch smart TV, and a private balcony overlooking the pool or garden. Rates start from RM450/night, inclusive of breakfast for two."},
    {"doc_type": "rooms", "title": "Deluxe Twin Room — Layout & Amenities",
     "content": "Q: Do you have twin bed rooms?\nA: Certainly! Our Deluxe Twin (42 sqm) features two super-single beds with the same premium amenities as our Deluxe King — rain shower, Nespresso machine, smart TV, and balcony. Perfect for friends travelling together or families with older children. From RM450/night with breakfast."},
    {"doc_type": "rooms", "title": "Executive Suite — Premium Experience",
     "content": "Q: Tell me about the Executive Suite.\nA: The Executive Suite (68 sqm) is our most popular upgrade — you'll enjoy a separate living area, a king bed, luxurious soaking tub alongside a rain shower, dual vanity, premium minibar, and a wraparound balcony with panoramic views. Includes Executive Lounge access with evening cocktails and canapés. From RM850/night."},
    {"doc_type": "rooms", "title": "Presidential Suite — Ultimate Luxury",
     "content": "Q: What's your best room?\nA: Our Presidential Suite (120 sqm) is the crown jewel — private dining room seating 8, full kitchenette, master bedroom with walk-in wardrobe, marble bathroom with jacuzzi and separate rain shower, butler service, and a wraparound terrace. Priced from RM2,500/night. Shall I check availability for your dates?"},
    {"doc_type": "rooms", "title": "Superior Room — Value Option",
     "content": "Q: What's your most affordable room?\nA: Our Superior Room (32 sqm) offers excellent value — king or twin configuration, rain shower, complimentary Wi-Fi, 43-inch smart TV, and garden view. A wonderful base for exploring the area. From RM320/night with breakfast for two."},
    {"doc_type": "rooms", "title": "Family Suite — For Parents with Kids",
     "content": "Q: Do you have family rooms?\nA: Yes! Our Family Suite (72 sqm) is designed exactly for this — a master bedroom with king bed connected to a kids' room with twin beds and child-friendly décor. Both rooms have their own TV and bathroom. We also provide complimentary baby cots and bed guards on request. From RM950/night."},
    {"doc_type": "rooms", "title": "Connecting Rooms — Multiple Rooms",
     "content": "Q: Can we book two rooms that connect?\nA: Of course! We have connecting Deluxe rooms available on floors 3–8. They share an internal door so families or groups can move between rooms easily while maintaining privacy. I'd recommend booking early as these are very popular. Shall I check availability?"},
    {"doc_type": "rooms", "title": "Room View Options",
     "content": "Q: What views are available?\nA: We offer three view categories: Garden View (lush tropical landscaping), Pool View (overlooking our infinity pool and deck), and Sea View (direct ocean panorama). Sea View rooms carry a RM80/night supplement. Pool View is complimentary for bookings of 3 nights or more — just our little way of saying thank you!"},
    {"doc_type": "rooms", "title": "Bed Configuration",
     "content": "Q: Can I request a king bed instead of twins?\nA: Absolutely! Bed configuration can be changed upon request for most room types, subject to availability. Just let us know at least 48 hours before arrival and we'll have it arranged for you. No extra charge at all."},
    {"doc_type": "rooms", "title": "Extra Bed & Rollaway",
     "content": "Q: Can you add an extra bed?\nA: Yes, we can add a rollaway bed to most room types for RM120/night including breakfast. Maximum one extra bed per room for comfort and safety. For children under 6, we provide complimentary baby cots. Just let us know when you book!"},
    {"doc_type": "rooms", "title": "Room Size Comparison",
     "content": "Q: How big are the rooms?\nA: Here's a quick comparison:\n• Superior: 32 sqm\n• Deluxe (King/Twin): 42 sqm\n• Executive Suite: 68 sqm\n• Family Suite: 72 sqm\n• Presidential Suite: 120 sqm\nAll rooms feel spacious with floor-to-ceiling windows flooding them with natural light."},
    {"doc_type": "rooms", "title": "Smoking vs Non-Smoking Rooms",
     "content": "Q: Do you have smoking rooms?\nA: All our rooms are non-smoking for the comfort of all guests. We have a designated outdoor smoking area on the ground floor near the garden terrace. Thank you for your understanding!"},
    {"doc_type": "rooms", "title": "Room Amenity List — Complete",
     "content": "Q: What amenities come with the room?\nA: Every room includes: high-speed Wi-Fi, Nespresso machine with daily capsule refill, minibar, electronic safe large enough for a laptop, iron and board, hairdryer, premium toiletries (locally sourced Malaysian brand), plush bathrobes and slippers, daily housekeeping with turndown service, and a universal power adapter on loan."},
    {"doc_type": "rooms", "title": "Pillow Menu",
     "content": "Q: Can I choose my pillow type?\nA: We'd be happy to accommodate! Our pillow menu includes: Memory foam, Down feather, Buckwheat hull, Hypoallergenic synthetic, and Bolster. Just let housekeeping know or call extension 0 — we'll deliver your preferred pillow within 15 minutes."},
    {"doc_type": "rooms", "title": "Room Temperature & Air Conditioning",
     "content": "Q: Can I control the aircon in my room?\nA: Yes, each room has individual climate control. You can adjust temperature between 16°C–28°C. If you'd prefer a fan or extra blankets, our housekeeping team is happy to provide them — just dial extension 0."},
    {"doc_type": "rooms", "title": "In-Room Safe",
     "content": "Q: Is there a safe in the room?\nA: Yes, every room has an electronic in-room safe that fits a standard laptop. Located inside the wardrobe. We also offer a complimentary safe deposit box at the front desk for larger or more valuable items."},
    {"doc_type": "rooms", "title": "Room Upgrade on Arrival",
     "content": "Q: Can I upgrade when I check in?\nA: Subject to availability, absolutely! Our front desk team will always check if an upgrade is available for you. Upgrade pricing on arrival is typically discounted compared to booking directly. Loyalty members get priority upgrades — another great reason to join our programme!"},
    {"doc_type": "rooms", "title": "Accessible Rooms",
     "content": "Q: Do you have wheelchair-accessible rooms?\nA: Yes, we have 6 fully accessible rooms on the ground floor. These feature wider doorways (90cm), roll-in showers with grab bars, lowered amenities, visual fire alarms, and emergency pull cords. Please mention this when booking so we can reserve one for you."},
    {"doc_type": "rooms", "title": "Balcony vs No Balcony",
     "content": "Q: Do all rooms have a balcony?\nA: Deluxe rooms and above all come with a private balcony or terrace. Our Superior rooms have large windows but no balcony. If outdoor space is important to you, I'd recommend the Deluxe — the upgrade is just RM130/night and definitely worth it for the morning coffee views!"},
    {"doc_type": "rooms", "title": "Room Renovation Status",
     "content": "Q: Are you renovating any part of the hotel?\nA: Great question! Our East Wing rooms were fully refreshed in 2025 with brand new furnishings, rain showers, and smart TVs. All other areas are in excellent condition. We always ensure any maintenance work happens during the day and never impacts your stay."},
    {"doc_type": "rooms", "title": "TV Channels & Streaming",
     "content": "Q: What channels does the TV have?\nA: All our smart TVs offer 100+ international channels including CNN, BBC, sports packages (Astro equivalent), and kids' channels. You can also cast from your personal Netflix, YouTube, or Disney+ account directly to the TV via Chromecast built-in."},
    {"doc_type": "rooms", "title": "Toiletries & Bathroom Amenities",
     "content": "Q: What toiletries do you provide?\nA: We provide a full set of premium toiletries — shampoo, conditioner, body wash, hand soap, body lotion, shower cap, cotton buds, dental kit, razor kit, and sewing kit. Our products are locally sourced and eco-friendly. We're happy to provide extras on request!"},
    {"doc_type": "rooms", "title": "Power Outlets & USB Charging",
     "content": "Q: Are there enough charging points?\nA: Each room has at minimum 6 power outlets (universal type with UK/US/EU adaptors built in) plus USB-A and USB-C charging ports on both bedside tables. We also have universal adaptors available at the front desk."},
    {"doc_type": "rooms", "title": "Room Service Hours",
     "content": "Q: Is room service 24 hours?\nA: Room service is available from 6:30 AM to midnight with our full menu. Between midnight and 6:30 AM, we offer a limited night menu featuring sandwiches, soups, desserts, and beverages. Orders typically arrive within 25–30 minutes."},
    {"doc_type": "rooms", "title": "Minibar Contents & Pricing",
     "content": "Q: What's in the minibar and how much does it cost?\nA: The minibar includes soft drinks (RM8–12), local craft beer (RM18), wine miniatures (RM25), chocolate bars (RM10), nuts (RM12), and instant noodles (RM8). Bottled water is replenished daily complimentary. A full price list is in the minibar folder."},
    {"doc_type": "rooms", "title": "Iron & Laundry in Room",
     "content": "Q: Is there an iron in the room?\nA: Every room has an iron and ironing board in the wardrobe. We also offer same-day laundry and dry cleaning service if you prefer — items collected before 9 AM are returned by 6 PM. Express 3-hour service is available at a 50% surcharge."},
    {"doc_type": "rooms", "title": "Noise Levels & Quiet Rooms",
     "content": "Q: Which rooms are quietest?\nA: For the most peaceful stay, we'd recommend rooms on floors 6–8 facing the garden side. These are furthest from the pool area and lobby. If you're a light sleeper, just let us know when booking and we'll allocate accordingly. We also have earplugs available at the front desk."},
    {"doc_type": "rooms", "title": "Do Not Disturb & Privacy",
     "content": "Q: How do I set do not disturb?\nA: You can activate the electronic DND sign from the panel by your door. When activated, housekeeping will skip your room. If you'd like service at a specific time, just let the front desk know and we'll schedule it around your preference."},
    {"doc_type": "rooms", "title": "Interconnecting Suites for Groups",
     "content": "Q: We're a group of 10, what do you suggest?\nA: For a group of 10, I'd recommend our Interconnecting Suite Package — 3 Deluxe rooms with connecting doors plus a separate Executive Suite as your gathering base. We can offer a 15% group discount and arrange a private dining setup. Shall I prepare a custom quotation?"},
    {"doc_type": "rooms", "title": "Honeymoon Room Setup",
     "content": "Q: We're on our honeymoon, any special touches?\nA: Congratulations! We'd love to make it extra special. Our complimentary honeymoon package includes: rose petal turndown, a bottle of sparkling wine, chocolate-dipped strawberries, late checkout until 2 PM, and a personal card from our team. Just let us know when booking!"},

    # ═══════════════════════════════════════════════════════════════
    # RATES — Pricing, Packages, Promotions (~60)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "rates", "title": "Standard Room Rates Overview",
     "content": "Q: What are your room rates?\nA: Here are our current rates (per night, inclusive of breakfast for 2):\n• Superior Room: from RM320\n• Deluxe King/Twin: from RM450\n• Executive Suite: from RM850\n• Family Suite: from RM950\n• Presidential Suite: from RM2,500\nRates may vary during peak seasons. Would you like me to check rates for your specific dates?"},
    {"doc_type": "rates", "title": "Weekend vs Weekday Rates",
     "content": "Q: Are weekends more expensive?\nA: Weekday rates (Sun–Thu) are our standard rates. Friday and Saturday nights carry a 15–20% weekend supplement. For the best value, consider a midweek stay or book in advance for our early bird discounts. Happy to check specific dates for you!"},
    {"doc_type": "rates", "title": "Best Available Rate Guarantee",
     "content": "Q: Will I get the best rate booking directly?\nA: Absolutely! We guarantee our best rates when you book directly with us. If you find a lower rate on any third-party site (for the same room, same dates, same conditions), we'll match it and give you a complimentary room upgrade. That's our Best Rate Promise."},
    {"doc_type": "rates", "title": "Long Stay Discount",
     "content": "Q: Do you have discounts for longer stays?\nA: Yes! We offer tiered long-stay discounts:\n• 3–4 nights: 10% off\n• 5–7 nights: 15% off\n• 8–14 nights: 20% off\n• 15+ nights: Custom rate (please contact us)\nThese apply to our Best Available Rate and include daily breakfast."},
    {"doc_type": "rates", "title": "Early Bird Offer",
     "content": "Q: Do you have early booking discounts?\nA: Book 60 days or more in advance and enjoy 25% off our standard rates. Book 30 days ahead for 15% off. Both include complimentary late check-out until 2 PM. This is our best-selling offer — highly recommended!"},
    {"doc_type": "rates", "title": "Last Minute Rates",
     "content": "Q: Any last-minute deals?\nA: We do! Check-in within the next 48 hours and enjoy up to 30% off available rooms, subject to occupancy. Follow us on social media where we announce flash sales. Would you like me to check what's available right now?"},
    {"doc_type": "rates", "title": "Breakfast Included or Not",
     "content": "Q: Is breakfast included?\nA: All our published rates include daily breakfast for 2 adults at Horizon Café (buffet). Additional adult breakfast is RM55/person. Children aged 6–12 enjoy breakfast at RM30, and children under 6 eat free. Room-only rates without breakfast are available at a RM80/night reduction."},
    {"doc_type": "rates", "title": "Half Board & Full Board",
     "content": "Q: Do you offer full board packages?\nA: Yes! Our meal packages include:\n• Half Board (breakfast + dinner): add RM120/person/night\n• Full Board (breakfast + lunch + dinner): add RM200/person/night\nDining is at Horizon Café and Sunset Grill. These represent excellent savings versus dining à la carte."},
    {"doc_type": "rates", "title": "Corporate Rates",
     "content": "Q: Do you have corporate rates?\nA: We offer negotiated corporate rates starting from RM380/night for Deluxe rooms with breakfast. This includes complimentary meeting room usage for 2 hours/day and 20% off F&B. We'd be happy to set up a corporate account — I can connect you with our sales team?"},
    {"doc_type": "rates", "title": "Government Rates",
     "content": "Q: Do you offer government rates?\nA: Yes, we honour government rates at RM250/night for Superior rooms and RM350/night for Deluxe rooms, inclusive of breakfast and subject to valid government ID presentation at check-in. These rates are available year-round except during public holiday periods."},
    {"doc_type": "rates", "title": "Seasonal Rate Changes",
     "content": "Q: When are your peak season rates?\nA: Peak rates apply during: school holidays (March, Jun–Jul, Nov–Dec), Chinese New Year, Hari Raya, Deepavali, and Christmas/New Year period. Peak surcharge is typically 30–50% above standard rates. For the best value, book during our shoulder season (Feb, Apr, Sep–Oct)."},
    {"doc_type": "rates", "title": "OTA vs Direct Booking",
     "content": "Q: I saw a cheaper rate on Booking.com\nA: Thank you for letting us know! We guarantee our best rate when booking direct. If you've found a lower rate on a third-party site for identical dates and conditions, please share the screenshot and we'll not only match it but include a complimentary upgrade. Booking direct also means free cancellation up to 48 hours before arrival."},
    {"doc_type": "rates", "title": "Child Pricing Policy",
     "content": "Q: How much for children?\nA: Children under 6 stay and eat breakfast free when sharing existing bedding with parents. Children 6–12 are charged RM80/night including breakfast (using existing bedding) or RM120/night with an extra bed. Children 13+ are charged at adult rates."},
    {"doc_type": "rates", "title": "Group Booking Rates",
     "content": "Q: Any discount for group bookings?\nA: Absolutely! For groups of 5+ rooms, we offer:\n• 5–9 rooms: 10% group discount\n• 10–19 rooms: 15% group discount + 1 complimentary room\n• 20+ rooms: 20% group discount + 2 complimentary rooms + private meeting space\nShall I connect you with our group reservations coordinator?"},
    {"doc_type": "rates", "title": "Wedding Package Rates",
     "content": "Q: How much is a wedding package?\nA: Our wedding packages start from RM15,000 for 100 pax (grand ballroom, 8-course dinner, basic décor, sound system). Premium packages from RM25,000 include floral arrangements, live band space, and complimentary bridal suite. We can fully customise — would you like to meet our wedding planner?"},
    {"doc_type": "rates", "title": "Day Use Room Rates",
     "content": "Q: Can I book a room just for the day?\nA: Yes! Our Day Use package is available from 10 AM–6 PM at 50% of the nightly rate. This includes full use of all room amenities, pool, and gym. Popular with business travellers between meetings or anyone needing a refreshing break. Subject to availability."},
    {"doc_type": "rates", "title": "Monthly Stay Rates",
     "content": "Q: What about monthly rates?\nA: For stays of 30 nights or more, we offer special long-term rates from RM6,500/month for a Deluxe room with daily breakfast and weekly housekeeping. Executive Suites from RM15,000/month. These include laundry credits and gym access. Let me prepare a detailed proposal for you."},
    {"doc_type": "rates", "title": "Taxes & Service Charge",
     "content": "Q: Are your rates inclusive of tax?\nA: All published rates are nett — inclusive of 10% service charge and 8% tourism tax (SST). There are no hidden charges. The only additional costs would be minibar consumption, spa treatments, or any optional add-ons you choose."},
    {"doc_type": "rates", "title": "Payment Methods Accepted",
     "content": "Q: What payment methods do you accept?\nA: We accept Visa, Mastercard, American Express, UnionPay, JCB, online banking (FPX), GrabPay, Touch 'n Go eWallet, and cash (MYR). A pre-authorisation hold is placed on credit cards at check-in for incidentals. Wire transfers are accepted for group bookings."},
    {"doc_type": "rates", "title": "Deposit & Cancellation Terms",
     "content": "Q: Do I need to pay a deposit?\nA: Standard bookings require a first-night deposit upon confirmation. Free cancellation up to 48 hours before arrival. Cancellations within 48 hours will forfeit the first night's charge. Peak season and promotional rates may have different terms — we'll always make these clear at booking."},
    {"doc_type": "rates", "title": "Resort Credit Package",
     "content": "Q: Do you have any all-inclusive type packages?\nA: While we're not fully all-inclusive, our Resort Credit Package is very popular — book 3 nights and receive RM300 resort credit to use on dining, spa, or activities. 5 nights gets you RM600 credit. It's a great way to enjoy everything without worrying about individual charges!"},

    # ═══════════════════════════════════════════════════════════════
    # RESERVATIONS — Booking FAQs (~80)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "faqs", "title": "How to Book a Room",
     "content": "Q: How do I book a room?\nA: You can book directly through our website, via WhatsApp (you're already here!), by phone, or email. Booking through WhatsApp or our website guarantees you the best available rate plus free cancellation up to 48 hours before arrival. Just let me know your preferred dates and room type!"},
    {"doc_type": "faqs", "title": "Booking Confirmation",
     "content": "Q: How will I receive my booking confirmation?\nA: Once confirmed, you'll receive a booking confirmation via email within 5 minutes. This includes your booking reference, room details, check-in/out times, and any special requests noted. If you booked via WhatsApp, I'll also send you a summary right here."},
    {"doc_type": "faqs", "title": "Modifying a Reservation",
     "content": "Q: Can I change my booking dates?\nA: Of course! You can modify your reservation free of charge up to 48 hours before your original check-in date, subject to availability. If the new dates have a different rate, we'll adjust accordingly. Just share your booking reference and I'll sort it out for you."},
    {"doc_type": "faqs", "title": "Cancellation Policy",
     "content": "Q: What's your cancellation policy?\nA: For standard bookings: free cancellation up to 48 hours before arrival. Within 48 hours, the first night is charged. No-shows are charged the full stay. Promotional and peak-season bookings may have stricter policies — these are always communicated clearly at the time of booking."},
    {"doc_type": "faqs", "title": "Booking for Someone Else",
     "content": "Q: Can I book for someone else?\nA: Absolutely! Just provide the guest's full name as it appears on their IC/passport. We'll note you as the booking contact. The guest will need to present valid photo ID at check-in. If you'd like to prepay as a gift, we can arrange that too."},
    {"doc_type": "faqs", "title": "Special Requests at Booking",
     "content": "Q: Can I request a specific room or floor?\nA: We're happy to note your preferences — high floor, quiet room, near the lift, etc. While we can't guarantee specific room numbers, we make every effort to accommodate your wishes. The earlier you book, the better chance we can fulfil your request!"},
    {"doc_type": "faqs", "title": "Booking Without Credit Card",
     "content": "Q: Can I book without a credit card?\nA: For WhatsApp or phone bookings, you can secure your reservation with a bank transfer of the first night's deposit. We'll send you our bank details. The transfer should be completed within 24 hours to confirm the booking. At check-in, we accept all major payment methods."},
    {"doc_type": "faqs", "title": "Walk-In Availability",
     "content": "Q: Can I just walk in without a reservation?\nA: Walk-ins are welcome and subject to availability! However, we strongly recommend booking in advance — especially during weekends and school holidays when we often reach full occupancy. Pre-booking also guarantees you our best rate."},
    {"doc_type": "faqs", "title": "ID Required at Check-In",
     "content": "Q: What ID do I need to check in?\nA: Malaysian guests need to present their MyKad (IC). International guests need to present their passport. All guests above 18 must be registered per government regulation. We'll make the process as quick and smooth as possible for you."},
    {"doc_type": "faqs", "title": "Minimum Age for Check-In",
     "content": "Q: What's the minimum age to check in?\nA: The primary guest must be at least 18 years old with a valid IC or passport. Guests under 18 must be accompanied by a registered adult. This is a standard policy for the safety and comfort of all our guests."},
    {"doc_type": "faqs", "title": "Reservation for Malaysian vs Foreign Guest",
     "content": "Q: Do you offer different rates for Malaysians and foreigners?\nA: Our published rates are the same for all guests. However, as a Malaysian-owned property, we occasionally run 'Cuti-Cuti Malaysia' promotions exclusively for MyKad holders. Follow us on social media for these special offers!"},
    {"doc_type": "faqs", "title": "Booking via WhatsApp Confirmation Process",
     "content": "Q: Can I confirm my booking through WhatsApp?\nA: Absolutely! Once you share your preferred dates, room type, and guest details, I'll send you a booking summary with the total cost. Upon your confirmation, I'll generate a booking reference and send you a formal confirmation via email. Easy and convenient!"},

    # ═══════════════════════════════════════════════════════════════
    # CHECK-IN / CHECK-OUT — Policies (~40)
    # ═══════════════════════════════════════════════════════════════
    {"doc_type": "policies", "title": "Standard Check-In & Check-Out Times",
     "content": "Q: What time is check-in and check-out?\nA: Check-in is from 3:00 PM and check-out is at 12:00 PM (noon). If you arrive earlier, our lobby lounge and facilities are available while your room is being prepared. Luggage storage is complimentary."},
    {"doc_type": "policies", "title": "Early Check-In Request",
     "content": "Q: Can I check in early?\nA: We'll do our best! Early check-in is subject to availability and can be requested at booking. If your room is ready before 3 PM, we'll let you in at no extra charge. Guaranteed early check-in from 10 AM is available for RM150. We'll always try to accommodate you."},
    {"doc_type": "policies", "title": "Late Check-Out Request",
     "content": "Q: Can I check out late?\nA: Of course — subject to availability:\n• Until 2 PM: complimentary for loyalty members / upon request\n• Until 4 PM: 50% of nightly rate\n• Until 6 PM: 75% of nightly rate\n• Beyond 6 PM: full night's charge\nJust let the front desk know the evening before, and we'll confirm."},
    {"doc_type": "policies", "title": "Express Check-In",
     "content": "Q: Is there a fast check-in option?\nA: Yes! If you've pre-registered online (link sent via email 24 hours before arrival), you can skip the counter entirely. Just head straight to our Express Check-In kiosk in the lobby, scan your QR code, and collect your key card. Takes under 2 minutes!"},
    {"doc_type": "policies", "title": "Express Check-Out",
     "content": "Q: How does check-out work?\nA: Simply drop your key cards at the Express Check-Out box at the front desk — no waiting required. Your final invoice will be emailed within 30 minutes. If you prefer a detailed walkthrough of your charges, our team is happy to assist in person."},
    {"doc_type": "policies", "title": "Luggage Storage Before/After Stay",
     "content": "Q: Can I leave my luggage after check-out?\nA: Absolutely! We offer complimentary luggage storage on your check-in and check-out day. Extended storage for up to 7 days is available for RM20/bag/day. All items are stored securely in our dedicated luggage room with CCTV. Just present your claim tag to collect."},
    {"doc_type": "policies", "title": "Check-In for Late Arrivals",
     "content": "Q: We're arriving very late at night.\nA: No worries at all! Our front desk is staffed 24/7. Whether you arrive at midnight or 3 AM, we'll be here to welcome you with a warm smile. Just let us know your estimated arrival time so we can have everything ready — perhaps a welcome drink waiting in your room?"},
    {"doc_type": "policies", "title": "Two Guests in One Room",
     "content": "Q: Can more than 2 people stay in one room?\nA: Our standard Deluxe rooms accommodate a maximum of 2 adults plus 1 child under 12 (or with an extra bed at RM120/night). For 3 adults, we'd suggest the Executive Suite or two connecting Deluxe rooms. The Family Suite comfortably sleeps 2 adults and 2 children."},
    {"doc_type": "policies", "title": "Key Card Policy",
     "content": "Q: How many key cards do I get?\nA: We provide 2 key cards per room at check-in. Additional key cards can be issued at the front desk with valid ID verification. Lost key cards incur a replacement fee of RM20. Key cards also activate the room's electricity — please take them with you to save energy!"},
    {"doc_type": "policies", "title": "Guest Registration Requirement",
     "content": "Q: Do all guests need to register?\nA: Per Malaysian hospitality regulations, all guests above 12 years of age must be registered at check-in with a valid MyKad or passport. This is for security purposes. Registration is quick and painless — we'll have you settled in no time."},
    {"doc_type": "policies", "title": "Unmarried Couples Policy",
     "content": "Q: Can unmarried couples stay together?\nA: We welcome all guests regardless of marital status. There are no restrictions for adult guests sharing a room. All we require is valid photo ID from each registered guest at check-in. Your comfort and privacy are our priority."},
    {"doc_type": "policies", "title": "Visitor Policy",
     "content": "Q: Can I have visitors in my room?\nA: Visitors are welcome in the lobby and public areas. For room visits, all visitors must register at the front desk with valid ID and are welcome between 8 AM and 10 PM. Overnight visitors not registered as guests will be charged an additional guest fee. This ensures the safety and comfort of all our guests."},
]
