"""Add Twilio fields to Property

Revision ID: f59cbb6d5bd2
Revises: sd_001_add_soft_delete
Create Date: 2026-02-23 09:42:44.311237
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers
revision: str = 'f59cbb6d5bd2'
down_revision: Union[str, None] = 'sd_001_add_soft_delete'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_daily', sa.Column('inquiries_handled_by_ai', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analytics_daily', sa.Column('inquiries_handled_manually', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analytics_daily', sa.Column('cost_savings', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.alter_column('kb_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.add_column('properties', sa.Column('whatsapp_provider', sa.String(length=20), server_default='meta', nullable=False))
    op.add_column('properties', sa.Column('twilio_phone_number', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), server_default='25.00', nullable=False))
    op.add_column('properties', sa.Column('brand_vocabulary', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('required_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'required_questions')
    op.drop_column('properties', 'brand_vocabulary')
    op.drop_column('properties', 'hourly_rate')
    op.drop_column('properties', 'twilio_phone_number')
    op.drop_column('properties', 'whatsapp_provider')
    op.alter_column('kb_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_column('analytics_daily', 'cost_savings')
    op.drop_column('analytics_daily', 'inquiries_handled_manually')
    op.drop_column('analytics_daily', 'inquiries_handled_by_ai')
    # ### end Alembic commands ###
